#!/bin/bash
# *******************************{begin:header}********************************
#                fida - https://code.google.com/p/xml-snippets/
# *****************************************************************************
#
#       fida: an XML Revision Tracking and Version Control Software.
#
#       Copyright (C) 2012-2014 Jani Hautamaki <jani.hautamaki@hotmail.com>
#
#       Licensed under the terms of GNU General Public License v3.
#
#       You should have received a copy of the GNU General Public License v3
#       along with this program as the file LICENSE.txt; if not, please see
#       http://www.gnu.org/licenses/gpl-3.0.html
#
# ********************************{end:header}*********************************

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -cp ${MYDIR}/../build.dir/xmlsnippets.jar: xmlsnippets.fida.XidClient $@

